// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbxhbyhfqfgijdnprpff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieGhieWhmcWZnaWpkbnBycGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjE5NDMsImV4cCI6MjA2OTUzNzk0M30.3xt2jeeJ-k4tyycs4p0eNlqd12bDLpUQ_k7Oa3M_eiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});